# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_c', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CBaseLine',
            new_name='CBirth',
        ),
    ]
