# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-16 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_c', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinfantdata',
            name='c3c_cardiovascularano_diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cinfantdata',
            name='c3c_cnsano_diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cinfantdata',
            name='c3c_gastrointestinalano_diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cinfantdata',
            name='c3c_musculoskeletalano_diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cinfantdata',
            name='c3c_respiratoryano_diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cinfantdata',
            name='c3c_skinano_diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cinfantdata',
            name='c3c_urogenitalano_diagnosis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
