# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-18 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_c', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmother',
            name='c1m_delivery_compilation',
            field=models.BooleanField(default=False),
        ),
    ]
