# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-16 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_c', '0003_cinfantdata_c3c_herpesinf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinfantdata',
            name='c3c_sepsis_antibiotic',
            field=models.NullBooleanField(default=False),
        ),
    ]
