# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 12:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_c', '0003_auto_20170330_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinfantdata',
            old_name='c3c_coord_blood_analysis',
            new_name='c3c_cord_blood_analysis',
        ),
    ]
