# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-30 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_c', '0004_auto_20170330_1905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinfantdata',
            old_name='c3c_others_mobirdities',
            new_name='c3c_others_morbidities',
        ),
    ]
