# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-26 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_c', '0004_cinfantdata_c3c_sepsis_antibiotic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinfantdata',
            name='c3c_plurality',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Single'), ('2', 'Twin')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='cinfantdata',
            name='c3c_respiratory_diagnosis',
            field=models.CharField(blank=True, choices=[('1', 'Nenatal pneumonia'), ('2', 'Hyaline membrane disease'), ('3', 'Meconium aspiration syndrome'), ('4', 'others')], default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cinfantdata',
            name='c3c_respiratory_support',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '02 therapy (nasal/mask)'), ('2', 'CPAP'), ('3', 'Non-invasive IPPR'), ('4', 'Intubation/ETT')], default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cinfantdata',
            name='c3c_sex',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'male'), ('2', 'female'), ('3', 'indetermined')], default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cmother',
            name='c1m_delivery_method',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Unassisted vaginal birth'), ('2', 'vacuum'), ('3', 'Forceps'), ('4', 'C-section')], default='', max_length=1),
        ),
        migrations.AlterField(
            model_name='cmother',
            name='c1m_proteinuria',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Negative'), ('1', 'Positive +'), ('2', 'Positive ++'), ('3', 'Positive +++')], default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cplacentalsampling',
            name='c2m_placenta_shapes',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Eclipse'), ('2', 'Oval'), ('3', 'Other')], default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='cplacentalsampling',
            name='c2m_umbilical_cord',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Centre'), ('2', 'Marginal')], default='', max_length=1, null=True),
        ),
    ]
