# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=25)),
                ('date_admission', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Puskesmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puskesmas_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='puskesmas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Puskesmas'),
        ),
    ]
