from django.contrib import admin
from .models import *

# Register your models here.
admin.site.register(DInfant)
admin.site.register(D1InfantGrowth)
admin.site.register(D2InfantFeeding)
admin.site.register(D3InfantCardiovascular)
admin.site.register(D4InfantLungFunction)
admin.site.register(D5InfantBiological)
admin.site.register(D6CurrentSmoking)
admin.site.register(D7Infection)
admin.site.register(D8PollutantExposure)

admin.site.register(DInfant2)
admin.site.register(D1InfantGrowth2)
admin.site.register(D2InfantFeeding2)
admin.site.register(D3InfantCardiovascular2)
admin.site.register(D4InfantLungFunction2)
admin.site.register(D5InfantBiological2)
admin.site.register(D6CurrentSmoking2)
admin.site.register(D7Infection2)
admin.site.register(D8PollutantExposure2)

admin.site.register(DInfant3)
admin.site.register(D1InfantGrowth3)
admin.site.register(D2InfantFeeding3)
admin.site.register(D3InfantCardiovascular3)
admin.site.register(D4InfantLungFunction3)
admin.site.register(D5InfantBiological3)
admin.site.register(D6CurrentSmoking3)
admin.site.register(D7Infection3)
admin.site.register(D8PollutantExposure3)

admin.site.register(DInfant4)
admin.site.register(D1InfantGrowth4)
admin.site.register(D2InfantFeeding4)
admin.site.register(D3InfantCardiovascular4)
admin.site.register(D4InfantLungFunction4)
admin.site.register(D5InfantBiological4)
admin.site.register(D6CurrentSmoking4)
admin.site.register(D7Infection4)
admin.site.register(D8PollutantExposure4)
