# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-26 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='d8pollutantexposure',
            name='d8m_other_detail',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
