# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-06 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='d1infantgrowth',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d1infantgrowth',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d1infantgrowth2',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d1infantgrowth2',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d1infantgrowth3',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d1infantgrowth3',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d1infantgrowth4',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d1infantgrowth4',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d2infantfeeding',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d2infantfeeding',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d2infantfeeding2',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d2infantfeeding2',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d2infantfeeding3',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d2infantfeeding3',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d2infantfeeding4',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d2infantfeeding4',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d3infantcardiovascular',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d3infantcardiovascular',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d3infantcardiovascular2',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d3infantcardiovascular2',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d3infantcardiovascular3',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d3infantcardiovascular3',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d3infantcardiovascular4',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d3infantcardiovascular4',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d4infantlungfunction',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d4infantlungfunction',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d4infantlungfunction2',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d4infantlungfunction2',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d4infantlungfunction3',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d4infantlungfunction3',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d4infantlungfunction4',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d4infantlungfunction4',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d5infantbiological',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d5infantbiological',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d5infantbiological2',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d5infantbiological2',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d5infantbiological3',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d5infantbiological3',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d5infantbiological4',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d5infantbiological4',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d6currentsmoking',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d6currentsmoking',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d6currentsmoking2',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d6currentsmoking2',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d6currentsmoking3',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d6currentsmoking3',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d6currentsmoking4',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d6currentsmoking4',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d7infection',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d7infection',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d7infection2',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d7infection2',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d7infection3',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d7infection3',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d7infection4',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d7infection4',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d8pollutantexposure',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d8pollutantexposure',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d8pollutantexposure2',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d8pollutantexposure2',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d8pollutantexposure3',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d8pollutantexposure3',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d8pollutantexposure4',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d8pollutantexposure4',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
