# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-15 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_d', '0002_auto_20170912_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='d8pollutantexposure',
            name='d8m_pet_detail',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d8pollutantexposure2',
            name='d8m_pet_detail',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d8pollutantexposure3',
            name='d8m_pet_detail',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='d8pollutantexposure4',
            name='d8m_pet_detail',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
