# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_d', '0002_d8pollutantexposure_d8m_other_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='d8pollutantexposure',
            name='d8m_apartment_level_number',
            field=models.IntegerField(null=True),
        ),
    ]
