# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-02 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_d', '0003_d8pollutantexposure_d8m_apartment_level_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='d3infantcardiovascular',
            name='d3c_heart_abnormality_detail',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='d1infantgrowth',
            name='d1c_bcg_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth',
            name='d1c_dpt_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth',
            name='d1c_hep_b_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth',
            name='d1c_hib_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth',
            name='d1c_influenza_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth',
            name='d1c_ipv_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth',
            name='d1c_opv_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth',
            name='d1c_pneumococcus_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth',
            name='d1c_rotavirus_date',
            field=models.DateField(null=True),
        ),
    ]
