# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-16 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_d', '0004_auto_20170917_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='d7infection',
            name='d7c_blood_microorganism_exist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='d7infection',
            name='d7c_faecal_microorganism_exist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='d7infection',
            name='d7c_urine_microorganism_exist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='d7infection2',
            name='d7c_blood_microorganism_exist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='d7infection2',
            name='d7c_faecal_microorganism_exist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='d7infection2',
            name='d7c_urine_microorganism_exist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='d7infection3',
            name='d7c_blood_microorganism_exist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='d7infection3',
            name='d7c_faecal_microorganism_exist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='d7infection3',
            name='d7c_urine_microorganism_exist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='d7infection4',
            name='d7c_blood_microorganism_exist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='d7infection4',
            name='d7c_faecal_microorganism_exist',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='d7infection4',
            name='d7c_urine_microorganism_exist',
            field=models.NullBooleanField(),
        ),
    ]
