# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-17 01:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_d', '0006_auto_20170917_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='d7infection',
            name='d7c_contact',
        ),
        migrations.RemoveField(
            model_name='d7infection2',
            name='d7c_contact',
        ),
        migrations.RemoveField(
            model_name='d7infection3',
            name='d7c_contact',
        ),
        migrations.RemoveField(
            model_name='d7infection4',
            name='d7c_contact',
        ),
    ]
