# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-17 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_d', '0008_auto_20170917_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='d4infantlungfunction',
            old_name='d4c_fev_1st',
            new_name='d4c_fev1_1st',
        ),
        migrations.RenameField(
            model_name='d4infantlungfunction',
            old_name='d4c_fev_2nd',
            new_name='d4c_fev1_2nd',
        ),
        migrations.RenameField(
            model_name='d4infantlungfunction2',
            old_name='d4c_fev_1st',
            new_name='d4c_fev1_1st',
        ),
        migrations.RenameField(
            model_name='d4infantlungfunction2',
            old_name='d4c_fev_2nd',
            new_name='d4c_fev1_2nd',
        ),
        migrations.RenameField(
            model_name='d4infantlungfunction3',
            old_name='d4c_fev_1st',
            new_name='d4c_fev1_1st',
        ),
        migrations.RenameField(
            model_name='d4infantlungfunction3',
            old_name='d4c_fev_2nd',
            new_name='d4c_fev1_2nd',
        ),
        migrations.RenameField(
            model_name='d4infantlungfunction4',
            old_name='d4c_fev_1st',
            new_name='d4c_fev1_1st',
        ),
        migrations.RenameField(
            model_name='d4infantlungfunction4',
            old_name='d4c_fev_2nd',
            new_name='d4c_fev1_2nd',
        ),
    ]
