# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-24 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_d', '0009_auto_20170917_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d1infantgrowth',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth2',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth2',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth2',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth3',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth3',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth3',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth4',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth4',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d1infantgrowth4',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d2infantfeeding',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d2infantfeeding',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d2infantfeeding2',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d2infantfeeding2',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d2infantfeeding2',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d2infantfeeding3',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d2infantfeeding3',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d2infantfeeding3',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d2infantfeeding4',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d2infantfeeding4',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d2infantfeeding4',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d3infantcardiovascular',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d3infantcardiovascular',
            name='d3c_cineloops',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '4 chamber view'), ('2', '5 chamber view'), ('3', 'Parasternal long axis'), ('4', 'Short axis view')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d3infantcardiovascular',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d3infantcardiovascular2',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d3infantcardiovascular2',
            name='d3c_cineloops',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '4 chamber view'), ('2', '5 chamber view'), ('3', 'Parasternal long axis'), ('4', 'Short axis view')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d3infantcardiovascular2',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d3infantcardiovascular2',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d3infantcardiovascular3',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d3infantcardiovascular3',
            name='d3c_cineloops',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '4 chamber view'), ('2', '5 chamber view'), ('3', 'Parasternal long axis'), ('4', 'Short axis view')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d3infantcardiovascular3',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d3infantcardiovascular3',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d3infantcardiovascular4',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d3infantcardiovascular4',
            name='d3c_cineloops',
            field=models.CharField(blank=True, choices=[('', ''), ('1', '4 chamber view'), ('2', '5 chamber view'), ('3', 'Parasternal long axis'), ('4', 'Short axis view')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d3infantcardiovascular4',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d3infantcardiovascular4',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction',
            name='d4c_breath_shortness',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction',
            name='d4c_dry_cough',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction',
            name='d4c_phlegmy_cough',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction',
            name='d4c_rattly_chest',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction',
            name='d4c_runny_nose',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction',
            name='d4c_snoring',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction',
            name='d4c_stridor',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction',
            name='d4c_stuffed_nose',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction',
            name='d4c_wheeze',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction2',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction2',
            name='d4c_breath_shortness',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction2',
            name='d4c_dry_cough',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction2',
            name='d4c_phlegmy_cough',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction2',
            name='d4c_rattly_chest',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction2',
            name='d4c_runny_nose',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction2',
            name='d4c_snoring',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction2',
            name='d4c_stridor',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction2',
            name='d4c_stuffed_nose',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction2',
            name='d4c_wheeze',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction2',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction2',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction3',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction3',
            name='d4c_breath_shortness',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction3',
            name='d4c_dry_cough',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction3',
            name='d4c_phlegmy_cough',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction3',
            name='d4c_rattly_chest',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction3',
            name='d4c_runny_nose',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction3',
            name='d4c_snoring',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction3',
            name='d4c_stridor',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction3',
            name='d4c_stuffed_nose',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction3',
            name='d4c_wheeze',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction3',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction3',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction4',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction4',
            name='d4c_breath_shortness',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction4',
            name='d4c_dry_cough',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction4',
            name='d4c_phlegmy_cough',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction4',
            name='d4c_rattly_chest',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction4',
            name='d4c_runny_nose',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction4',
            name='d4c_snoring',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction4',
            name='d4c_stridor',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction4',
            name='d4c_stuffed_nose',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction4',
            name='d4c_wheeze',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'Not at all'), ('1', 'Once'), ('2', 'Twice'), ('3', '3 or more'), ('4', 'Every day')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction4',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d4infantlungfunction4',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d5infantbiological',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d5infantbiological',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d5infantbiological2',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d5infantbiological2',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d5infantbiological2',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d5infantbiological3',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d5infantbiological3',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d5infantbiological3',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d5infantbiological4',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d5infantbiological4',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d5infantbiological4',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking',
            name='d6f_smoking_frequency',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Daily'), ('2', 'Weekly'), ('3', 'Monthly'), ('0', 'Never')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking',
            name='d6f_smoking_status',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Smoker'), ('2', 'Ex-smoker'), ('0', 'Never smoke')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking',
            name='d6m_smoking_status',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Smoker'), ('2', 'Ex-smoker'), ('0', 'Never smoke')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking2',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking2',
            name='d6f_smoking_frequency',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Daily'), ('2', 'Weekly'), ('3', 'Monthly'), ('0', 'Never')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking2',
            name='d6f_smoking_status',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Smoker'), ('2', 'Ex-smoker'), ('0', 'Never smoke')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking2',
            name='d6m_smoking_status',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Smoker'), ('2', 'Ex-smoker'), ('0', 'Never smoke')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking2',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking2',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking3',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking3',
            name='d6f_smoking_frequency',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Daily'), ('2', 'Weekly'), ('3', 'Monthly'), ('0', 'Never')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking3',
            name='d6f_smoking_status',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Smoker'), ('2', 'Ex-smoker'), ('0', 'Never smoke')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking3',
            name='d6m_smoking_status',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Smoker'), ('2', 'Ex-smoker'), ('0', 'Never smoke')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking3',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking3',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking4',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking4',
            name='d6f_smoking_frequency',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Daily'), ('2', 'Weekly'), ('3', 'Monthly'), ('0', 'Never')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking4',
            name='d6f_smoking_status',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Smoker'), ('2', 'Ex-smoker'), ('0', 'Never smoke')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking4',
            name='d6m_smoking_status',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Smoker'), ('2', 'Ex-smoker'), ('0', 'Never smoke')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking4',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d6currentsmoking4',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d7infection',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d7infection',
            name='d7c_ward',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Emergency room only'), ('2', 'One day care'), ('3', 'General Ward'), ('4', 'High care/intensive care')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d7infection',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d7infection2',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d7infection2',
            name='d7c_ward',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Emergency room only'), ('2', 'One day care'), ('3', 'General Ward'), ('4', 'High care/intensive care')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d7infection2',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d7infection2',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d7infection3',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d7infection3',
            name='d7c_ward',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Emergency room only'), ('2', 'One day care'), ('3', 'General Ward'), ('4', 'High care/intensive care')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d7infection3',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d7infection3',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d7infection4',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d7infection4',
            name='d7c_ward',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Emergency room only'), ('2', 'One day care'), ('3', 'General Ward'), ('4', 'High care/intensive care')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d7infection4',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d7infection4',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure',
            name='d8m_garbage_burning',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'No'), ('1', 'Once per week or less'), ('2', 'More than once per week but not daily'), ('3', 'Daily')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure',
            name='d8m_housing_type',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Landed House'), ('2', 'Flat/Apartment')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure',
            name='d8m_landed_house_type',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'One story building'), ('2', 'More than one story building')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure2',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure2',
            name='d8m_garbage_burning',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'No'), ('1', 'Once per week or less'), ('2', 'More than once per week but not daily'), ('3', 'Daily')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure2',
            name='d8m_housing_type',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Landed House'), ('2', 'Flat/Apartment')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure2',
            name='d8m_landed_house_type',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'One story building'), ('2', 'More than one story building')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure2',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure2',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure3',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure3',
            name='d8m_garbage_burning',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'No'), ('1', 'Once per week or less'), ('2', 'More than once per week but not daily'), ('3', 'Daily')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure3',
            name='d8m_housing_type',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Landed House'), ('2', 'Flat/Apartment')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure3',
            name='d8m_landed_house_type',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'One story building'), ('2', 'More than one story building')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure3',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure3',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure4',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure4',
            name='d8m_garbage_burning',
            field=models.CharField(blank=True, choices=[('', ''), ('0', 'No'), ('1', 'Once per week or less'), ('2', 'More than once per week but not daily'), ('3', 'Daily')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure4',
            name='d8m_housing_type',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Landed House'), ('2', 'Flat/Apartment')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure4',
            name='d8m_landed_house_type',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'One story building'), ('2', 'More than one story building')], max_length=1),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure4',
            name='d_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms_d.DInfant'),
        ),
        migrations.AlterField(
            model_name='d8pollutantexposure4',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
    ]
