# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-19 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_b1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b1gestationalnutrition',
            old_name='b6m_other',
            new_name='b6m_other_med',
        ),
        migrations.RenameField(
            model_name='b1gestationalnutrition',
            old_name='b6m_other_duration',
            new_name='b6m_other_med_duration',
        ),
        migrations.RenameField(
            model_name='b1gestationalnutrition',
            old_name='b6m_other_routine',
            new_name='b6m_other_med_routine',
        ),
    ]
