# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-19 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_b1', '0002_auto_20170920_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b1gestationalnutrition',
            name='b6m_other_med',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
