# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-26 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_b1', '0004_auto_20170925_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b1currentsmookinghabits',
            name='b4m_smoking_status',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Smoker'), ('2', 'Ex-smoker'), ('0', 'Never smoke')], max_length=1),
        ),
    ]
