# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-01 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_a', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='a1motherdemographic',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='a1motherdemographic',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='a2motheremployment',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='a2motheremployment',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='a3obstetric',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='a3obstetric',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='a4father',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='a4father',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='a5prepregnancysmoking',
            name='created_by',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='a5prepregnancysmoking',
            name='edited_by',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
