# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-25 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_a', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a1motherdemographic',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='a1motherdemographic',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='a2motheremployment',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='a2motheremployment',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='a3obstetric',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='a3obstetric',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='a4father',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='a4father',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='a5prepregnancysmoking',
            name='created_time',
            field=models.CharField(blank=True, max_length=28),
        ),
        migrations.AlterField(
            model_name='a5prepregnancysmoking',
            name='updated_time',
            field=models.CharField(blank=True, max_length=28),
        ),
    ]
