# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-12 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_a', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abaseline',
            name='data_checked_id',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='abaseline',
            name='data_entry_id',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AlterField(
            model_name='abaseline',
            name='date_admission',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='abaseline',
            name='date_data_checked',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='abaseline',
            name='date_data_entered',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='abaseline',
            name='date_interviewed',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='abaseline',
            name='interviewer_id',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
