# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-14 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_a', '0002_auto_20170514_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a5prepregnancysmoking',
            name='a5c_colleagues_smoking_status',
            field=models.CharField(choices=[('1', 'Smoker'), ('2', 'Ex-smoker'), ('3', 'Never smoke')], default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='a5prepregnancysmoking',
            name='a5f_father_smoke_frequency',
            field=models.CharField(choices=[('1', 'Daily'), ('2', 'Weekly'), ('3', 'Monthly'), ('0', 'Never')], default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='a5prepregnancysmoking',
            name='a5f_father_smoking_status',
            field=models.CharField(choices=[('1', 'Smoker'), ('2', 'Ex-smoker'), ('3', 'Never smoke')], default='', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='a5prepregnancysmoking',
            name='a5m_mother_smoking_status',
            field=models.CharField(choices=[('1', 'Smoker'), ('2', 'Ex-smoker'), ('3', 'Never smoke')], default='', max_length=1, null=True),
        ),
    ]
