# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-14 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_a', '0003_auto_20170514_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a5prepregnancysmoking',
            name='a5c_colleagues_smoking_status',
            field=models.NullBooleanField(),
        ),
    ]
